# Generated by Django 3.0.5 on 2024-08-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20240722_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_pic',
            field=models.ImageField(default='static/profile_pic/teacher/teacher_default.jpeg', upload_to='static/profile_pic/Teacher/'),
        ),
    ]
