# Generated by Django 3.0.5 on 2024-08-28 05:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_auto_20240828_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='mobile',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{1,20}$', 'Only numeric characters are allowed.')]),
        ),
    ]
