# Generated by Django 3.0.5 on 2024-08-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_auto_20240828_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
