# Generated by Django 3.0.5 on 2024-08-30 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_teacher_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_visible',
        ),
    ]
