# Generated by Django 3.0.5 on 2024-09-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title',
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_name',
            field=models.CharField(default='Default Quiz Name', max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_marks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
