# Generated by Django 3.0.5 on 2024-09-03 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_auto_20240903_0505'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
