# Generated by Django 3.0.5 on 2024-09-04 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_remove_teacher_is_visible'),
        ('teacher', '0014_delete_quiz'),
    ]

    operations = [
    ]
