# Generated by Django 3.0.5 on 2024-09-11 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0016_auto_20240904_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='mobile',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Only digits allowed.', regex='^\\d+$')]),
        ),
    ]
