# Generated by Django 3.0.5 on 2024-08-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20201209_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
