# Generated by Django 3.0.5 on 2024-08-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quiz_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
