# Generated by Django 3.0.5 on 2024-09-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20240830_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
