# Generated by Django 3.0.5 on 2024-09-04 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20240903_0411'),
        ('quiz', '0008_auto_20240903_1339'),
    ]

    operations = [
    ]
