# Generated by Django 3.0.5 on 2024-08-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20240828_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/profile_pic/Student/student_default.jpeg', null=True, upload_to='static/profile_pic/Student/'),
        ),
    ]
