# Generated by Django 3.0.5 on 2024-08-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20240828_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_pic/Student/'),
        ),
    ]
