# Generated by Django 3.0.5 on 2024-08-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20240828_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(default='static/profile_pic/Student/student_default.jpeg', upload_to='static/profile_pic/Student/'),
        ),
    ]
