# Generated by Django 3.0.5 on 2024-08-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20240828_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(upload_to='static/profile_pic/Student/'),
        ),
    ]
