# Generated by Django 3.0.5 on 2024-09-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20240828_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pic/Student/'),
        ),
    ]
