# Generated by Django 3.0.5 on 2024-09-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20240903_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(upload_to='static/profile_pic/Student/'),
        ),
    ]
