# Generated by Django 3.0.5 on 2024-09-11 04:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20240911_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number containing only digits.', regex='^\\d+$')]),
        ),
    ]
